Deze pagina visualiseert het dossier<br />
Om een artikel te bewerken, klik op  <b>"bewerken"</b>.<br />
Om een artikel te bekijken, klik op de <b>titel van het artikel</b>.<br />
<br />
Het id dat je naast ieder artikel vindt, zal je toelaten om te beslissen wanneer je een artikel wil publiceren en in welk deel van de structuur. (Dit 
betekent dat je het zal moeten defini&euml;ren als "artikel waarnaar het moet linken").<br />
<br />
<hr />

