
<!-- start right column -->
<td bgcolor="#660000" width="4" class="bgcolor"><img src="/im/bump.gif"
width="4" height="1"></td>
<td width="160" bgcolor="#660000" valign="top" class="bgcolor">
<img src="/im/bump.gif" height="4" width="1" alt=""><br><table align="center"
width="100%" border="0" cellspacing="0"
cellpadding="0">
          <tr valign="top">
              <td><div class="hedl" align="left"><font size="1"
face="arial,helvetica,sans-serif"><strong>UPCOMING IMC COVERAGE</strong></font></div>
<font size="1" face="MS Sans Serif,arial,helvetica,sans-serif">
SF-IMC <a href="/calendar/">Local Event Calendar</a>
<hr noshade size="1"></font></td></tr><tr valign="top">
<td><center><font face="verdana,arial,helvetica,sans-serif" size="-1"><a href="/<? echo linkToNewswire(''); ?>"><strong>LATEST NEWSWIRE</a></strong></font>
                <br><img src="/images/b.gif" width=1 height=5 border=0><br clear=all>
               <img src="/images/media_legend.gif" width="112" height="28" border="0" usemap="#legend">
				<map name="legend"><!-- left-x,top-y,right-x,bottom-y -->
				    <area alt="latest articles" coords="1,1,62,14" href="/search-process.php3?medium=text">
				    <area alt="latest videos" coords="1,14,62,28" href="/search-process.php3?medium=video">
				    <area alt="latest photos" coords="63,1,112,15" href="/search-process.php3?medium=image">
				    <area alt="latest audio" coords="63,15,112,28" href="/search-process.php3?medium=audio">
				</map>

		<hr noshade size="1">
                <font face="verdana,arial,helvetica,sans-serif" size="-2"><a href="/publish.php">CLICK HERE TO PUBLISH YOUR NEWS!</a></font>
                <hr noshade size="1"></center>
<font face="arial,helvetica,sans-serif" size="-1">

<? include($local_cache_path."/summaries.html"); ?>

<a href="/display.php">MORE NEWS >></a>
</font>
              </td>
            </tr>
          </table>
<br><img src="/im/bump.gif" width="160" height="1" alt="" border="0"></td>
<td bgcolor="#660000" width="4" class="bgcolor"><img src="/im/bump.gif"
width="4"
height="1"></td>
<!-- /end right column -->
