<tr><td class="bg3"><table width="100%" border="0" cellspacing="0"
cellpadding="0"><tr>

<? include(SF_INSTALL_PATH . "/local/include/index_left.inc"); ?>

<td class="bgult" width="1"><img src="/im/bump.gif" width="1"  height="1"  
alt="" /></td><td valign="top"  class="bgcentercol"><table border="0"
cellspacing="0" cellpadding="4" width="100%"><tr><td width="100%"
valign="top"><table border="0" cellspacing="0" cellpadding="3"><tr><td>
