<?
//file containing the array creating the select for the hiding reason
// rememeber to edti as well teh common.dict for your language :)))))

       $reason_options = array(
                            "empty" => 'Empty',
                            "double" => 'Double',
                            "no info" => 'Not Contanining any info',
                            "fascist" => 'Fascist',
                            "racist" => 'Racist',
                            "sexist" => 'Sexist',
                            "provo" => 'Provocation',
                            "propaganda" => 'Propaganda',
                            "commercial" => 'Commercial',
                            "internal" => 'Hidden for internal use',
                            "insults and threats" => 'Insults or Threats',
                            "other" => 'Other'
                            );

?>
