&copy; 2000-2018 <?=$GLOBALS['site_name']?>. Unless otherwise stated by
the author, all content is free for non-commercial reuse, reprint, and
rebroadcast, on the net and elsewhere. Opinions are those of the
contributors and are not necessarily endorsed by the <?=$GLOBALS['site_name']?>. 
Running sf-active v<?=$GLOBALS['sfactive_version']?> 
<a href="/process/disclaimer.php">Disclaimer</a> | 
<a href="/process/privacy.php">Privacy</a>
