This page is a visualisation of your dossier.<br />
To edit an article, click on <b>"edit"</b>.<br />
To view an article click on <b>the title of the article</b>.<br />
<br />
The id that you see next to each article will allow you to decide where you want to publish an article in the dossier structure (This means that you 
will have to define it as "article to where you want to link to")<br />
<br />
<hr />

