Questa pagina visualizza l'albero di documenti del dossier.<br />
Per editare un articolo, cliccate su <b>"Editare"</b>.<br />
Per visualizzare un articolo, cliccate sul <b>titolo dell'articolo</b>.<br /><br />

L'id presente di fianco a ogni articolo vi consentira' di decidere quando pubblicate un articolo in quale ramo dell'albero includerlo (dovrete cioe' 
segnarlo come "Articolo a cui linkare".<br /><br />
<hr />

