<?php $category = $GLOBALS['category_id'] ; ?>
<table width="112"><tr><td><a 
href="/news/?category=<?=$category?>&amp;medium=text"><img align="middle" src="/im/imc_article.gif"
border="0"   alt="browse articles" /></a></td><td><a class="newswire"
href="/news/?category=<?=$category?>&amp;medium=text"><small>article</small></a></td><td><a
href="/news/?category_id=<?=$category?>&amp;medium=image"><img 
align="middle" src="/im/imc_photo.gif" border="0"   
alt="browse photos" /></a></td><td><a class="newswire" 
href="/news/?category_id_id=<?=$category?>&amp;medium=image"><small>photo</small></a></td></tr><tr><td><a 
href="/news/?category_id=<?=$category?>&amp;medium=video"><img 
align="middle" src="/im/imc_video.gif" border="0"  
alt="browse videos" /></a></td><td><a class="newswire"
href="/news/?category_id=<?=$category?>&amp;medium=video"><small>video</small></a></td><td><a
href="/news/?category_id=<?=$category?>&amp;medium=audio"><img 
align="middle" src="/im/imc_audio.gif" border="0"   
alt="browse audio" /></a></td><td><a class="newswire" 
href="/news/?category_id=<?=$category?>&amp;medium=audio"><small>audio</small></a></td></tr></table>
