<!-- publishing instructions -->

<p><strong>If you've read this before, <a href="#publishform">jump straight to the form</a>!</strong></p>

<p>Want to show off your photos of an event? Got audio or video that people just
have to see? This is the place to put it. We want to hear your story. Use any format you want, from journalistic, to academic, to
personal account.</p>

<p><span class="hed"><b>WHAT TO PUBLISH:</b></span> Please use this form to contribute new stories and ideas. We think comments
belong with the story being discussed. So to have your say in response to a story on the site, please use the "add your
comments" link at the bottom of each story. Instead of reposting corporate media articles to the site, try posting your own
critique or summary, short quotes, and links.</p>

<p><span class="hed"><b>LEGALESE:</b></span> Unless otherwise stated, all content contributed to this site is free for
non-commercial reuse, reprint or rebroadcast. If you want to specify different conditions, please do so in the summary, including any
© copyright statement. Please read our <a href="/process/privacy.php">privacy</a> and <a
href="/process/disclaimer.php">disclaimer</a> statements before continuing.</p>

<!-- <p><strong><span class="hed">THINGS TO KNOW:</span></strong> You can use this form to publish your article, picture, audio,
video, or just a URL.  Please focus on activism issues and events. The LA-IMC editorial collective may re-arrange the display of
submitted stories.</p> -->

<p><strong><span class="hed">MULTIMEDIA:</span></strong> Please scale your
images to a <b>width of no more than 600 pixels</b>.  If you need help
converting your sounds or video to a digital file, consult our <a
href="/process/resources/encoding.php">tutorial</a> page.  
QuickTime should be encoded as fast start, compressed
header.</p>

<p><strong><span class="hed">EDITORIAL POLICY:</span></strong> After
stories have been published, they can be edited, linked or hidden by the
collective running this site. We have a lot of respect for the people
publishing on our site, so we generally only use these features to fix
obvious mistakes, such as typos in a web address or a duplicate copy of a
story. Very rarely, someone abuses our trust by posting a story that is
way outside what the website is set up to do, and we may remove it. Read
more about our <b><a href="/process/openpub.php">open publishing
policy</a></b>.</p>

<!-- /publishing instructions -->
