<!-- publishing instructions -->

<p><strong>Si leiste esto antes, <a href="#publishform"> ve directo al formulario </a>!</strong></p>
<p>¿Querés mostrar fotografías de algún hecho? ¿Tenés audio o video para que otras 
  personas vean? Este es el lugar para colocarlo. Nosotros queremos conocer tu 
  historia. Podés utilizar el estilo que desees, desde el periodístico al académico 
  o al de una narración personal.</p>

<p><span class="hed"><b>QU&Eacute; COSAS PUBLICAR:</b></span>  Por favor utilizá 
  este formulario para contribuir con nuevas historias e ideas. Pensamos que los 
  comentarios que se realicen deben estar relacionados con la historia en discusión. 
  Para colocar tu opinión con respecto a una historia en el sitio, por favor us&aacute; 
  el enlace "agreg&aacute; tus comentarios" al final de cada historia. En lugar 
  de reenviar artículos de los medios de comunicación corporativos al sitio, trat&aacute; 
  de incluir tu propia crítica o resumen, citas cortas y enlaces.</p>
<p><span class="hed"><b>ASPECTOS LEGALES:</b></span> A menos que se establezca 
  explícitamente, todas las contribuciones a este sitio pueden reutilizarse, reimprimirse 
  o reproducirse con libertad pero solo con fines no comerciales. Si vos querés 
  especificar condiciones diferentes, por favor hacelo en el resumen, incluyendo 
  la declaración de derechos de autor que corresponda. Te agradecemos que leas 
  nuestra <a href="/process/privacy.php">declaración de privacidad</a> y <a href="/process/disclaimer.php">disclaimer</a> antes de continuar.</p>
<!-- <p><strong><span class="hed">COSAS PARA SABER:</span></strong> Podés usar este formulario para publicar tu artículo, imágenes, audio, video, o simplemente una dirección en la web. Por favor centrate en temas y acciones sociales y políticas. El colectivo editorial de IMC Uruguay puede reordenar y reagrupar la presentación de las historias recibidas.</p> -->
<p><strong><span class="hed">MULTIMEDIA:</span></strong> Si necesitás ayuda para 
  convertir tus registros de audio o video a formato digital, consultá nuestra  <a href="/process/resources/tutorial.php">página de ayuda</a>. . Nosotros brindamos 
  RealMedia vía RTSP para lograr mejores resultados. </p>
<p><strong><span class="hed">POLITICA EDITORIAL:</span></strong> Después de que 
  se han publicado las historias pueden ser editadas, enlazadas u ocultadas por 
  el colectivo que administra este sitio. Nosotros tenemos mucho respeto por las 
  personas que publican historias en el sitio, por lo que generalmente solo tomamos 
  estas medidas para corregir errores obvios, como un error en una dirección web 
  o la aparición repetida de una historia. Muy raramente alguien abusa de nuestra 
  confianza, anunciando una historia que no corresponde con la finalidad del sitio, 
  en tal caso podemos quitarla. Leé más sobre nuestra política respecto de la  <a href="/process/openpub.php">publicación abierta</a> policy.</p>
<!-- /publishing instructions -->
