<?php
        $temp_options = array(
                            "html_only" => "HTML (no &lt;br /&gt;)",
                            "html_row" => "HTML (&lt;br /&gt; only)",
                            "noimage_white" => "Plain (housing), No image",
                            "image_left_white" => "Plain (housing), Left image",
                            "image_right_white" => "Plain (housing), Right image",
                            "title_no_image_noclear" => "Title, No image, No clear",
                            "image_on_left_noclear" => "Title, Image on left, No clear",
                            "image_on_right_noclear" => "Title, Image on right, No clear",
                            "title_no_image_headlink" => "Title, No image, Link",
                            "image_on_left_headlink" => "Title, Image on left, Link",
                            "image_on_right_headlink" => "Title, Image on right, Link",
                            "title_no_image_row" => "Title, No image",
                            "image_on_left_row" => "Title, Image on left",
                            "image_on_right_row" => "Title, Image on right",
                            "image_on_left_no_title_row" => "No Title, Image on left",
                            "image_on_right_no_title_row" => "No Title, Image on Right"
                            );
?>
