<a href="/"><?=$GLOBALS['site_crumb']?></a> : <a href="/process/">process</a> : about

<p>The <?=$GLOBALS['site_name']?> is a non-commercial, democratic
collective of bay area independent media makers and media outlets, and
serves as the local organizing unit of the global <a
href="http://www.indymedia.org/">Indymedia</a> network. </p>

<h3>Principles of Unity: <?=$GLOBALS['site_name']?></h3>

<ol><li>We strive to provide an information infrastructure for people and
opinions who do not have access to the airwaves, tools and resources of
corporate media. This includes audio, video, photography, internet
distribution and any other communication medium.</li>

<li>We support local, regional and global struggles against exploitation
and oppression.</li>

<li>We function as a non-commercial, non-corporate, anti-capitalist
collective.</li></ol>

<p><?=$GLOBALS['site_name']?> involves volunteer participants and allied
collectives organized along anti-authoritarian principles of open and
transparent decision-making processes, including open public meetings; a
form of modified consensus; and the elimination of hierarchies.</p>
 
<p><?=$GLOBALS['site_name']?> participants shall not act in a manner that
endangers, intimidates, or physically harms any member of the group,
including by sexual harassment or acts of violence. Indymedia members
shall strive to act in a respectful manner to other members of the
collective as well as the public.</p>

<h3>Mission Statement</h3>

<ul><li>To encourage a world where globalization is not about homogeneity
and exploitation, but rather, about diversity and cooperation.</li>

<li>To cover local events that are ignored or poorly covered by corporate
media.</li>

<li>To provide edited audio, video, and print stories of the above on the
internet for independent media outlets and the general public.</li>

<li>To facilitate the networking and coordination for the coverage of
local events as well as gather information about events to cover.</li>

<li>To provide links to alternative media, activist, and research
groups.</li>

<li>To seek out and provide coverage underscoring the global nature of
people's struggles for social, economic, and environmental justice
directly from their perspective.</li>

<li>To offer community classes for training in internet and media
skills.</li>

<li>To encourage, facilitate, and support the creation of independent news
gathering and organizations.</li></ul>

<h3>Get Involved</h3>

<p>This is <em>your</em> independent media center. As an all-volunteer
organization, we need <strong>you</strong> to get involved!  Introduce
yourself at our <a href="http://volunteer.indymedia.org/">volunteer signup
page</a> and check our <a href="/process/contact.php">contact</a> page for
info on meetings and e-mail lists.</p>

<p><small>Last updated <?php echo date("r",filemtime(SF_CACHE_PATH.'/pages/about.inc')); ?></small></p>

<a href="/"><?=$GLOBALS['site_crumb']?></a> : <a 
href="/process/">process</a> : about <a href="#top">(top)</a>
