<h1>Cleaner Tutorial</h1>

<ol>
<li>open your file in Media Cleaner (make sure no other files are open 
- you can get rid of other people's files by highlighting them and hitting
"Delete"). Files compatible with Cleaner include QuickTime movies, 
Final Cut Pro movies, and raw captured clips in the iMovie Media 
folder or Final Cut Pro Capture Scratch folder.</li>
<li>go to windows 
menu and click Settings Wizard</li> <li>click WWW; continue.</li>
<li>click RealVideo; continue.</li>
<li>click Streaming; continue.</li>
<li>click "28.8, 33.6 Modem", "56k modem (ISDN single)", "ISDN
(Dual)", and if you want (this will make your file much larger), the next 
highest bandwidth; continue.</li>
<li>click on the appropriate setting for the importance of audio & video,
and
the type of soundtrack material; continue.</li>
<li>click on 0 to 4 of these video options - it's up to you! each of these
options involves some sacrifices, so if you click on two,
you will get something halfway between, not both. continue.</li>
<li>normalize audio should be on. if needed, click on "noise reduction"
and
fade in/out; finish.</li>
<br><br>by the way, if you know what you're doing, you can click on
"Advanced
Settings" in the windows menu to customize all settings.<br><br>

<li>you can crop your video (for instance, if you have a talking head with
too much head room) by clicking and dragging on the video in the "Source"
window.</li>

<li>click "Start" to begin processing.</li>

<li>click "ok" if it asks you about your RealVideo streaming server - the
sf.indymedia server will take care of this automatically.</li>

<li>your .rm file can now be <a href="/publish.php">uploaded</a>. Any
.ram and .html files created by Media Cleaner can be deleted - the
sf.indymedia server will generate these automatically.</li>

</ol>

<div>
	<small>Last updated <?php echo date("r",filemtime($_SERVER['SCRIPT_FILENAME'])); ?></small>
</div>
