<div class="bcrumb">
	<a href="/">sf-imc</a> : legal info
</div>

<h4>Disclaimer</h4>
<p>Content (text, image, audio, or video) posted to the <?=$GLOBALS['site_nick']?> web site is owned by its author. Unless otherwise stated by the author, all content is free for non-commercial reuse, reprint, and rebroadcast, on the net and elsewhere. Opinions are those of the people contributing to the site and are not necessarily endorsed by the <?=$GLOBALS['site_nick']?>. As an all-volunteer organization, the <?=$GLOBALS['site_nick']?> does not have the means to guarantee the accuracy of news or opinions posted to the newswire.</p>

<h4>No Warranty</h4>
<p>Because, unless otherwise stated, site content is licensed free of charge for non-commercial use, there is no warranty for the content. Except when otherwise stated in writing, the <?=$GLOBALS['site_nick']?> collective and/or other parties provide the content "as is" without warranty of any kind, either expressed or implied, including, but not limited to, the implied warranties of merchantability and fitness for a particular purpose. The entire risk of use of the content is with you. Should the content prove faulty, inaccurate, or otherwise unacceptable you assume the cost of all necessary repair or correction.</p>
<p>In no event unless agreed to in writing will the <?=$GLOBALS['site_nick']?> collective, or any other party who may mirror and/or redistribute the content as permitted above, be liable to you for damages, including any general, special, incidental or consequential damages arising out of the use or inability to use the content, even if the <?=$GLOBALS['site_nick']?> collective or other party has been advised of the possibility of such damages.</p>

<h4>Copyright</h4>
<p>The compilation and presentation of site content is &copy; 2000-2003 <?=$GLOBALS['site_name']?></p>
<div><small>Last updated <?php echo date("r",filemtime($_SERVER['SCRIPT_FILENAME'])); ?></small></div>
<br>
<div class="bcrumb"><a href="/">sf-imc</a> : legal info</div><br>

