<a href="/"><?=$GLOBALS['site_crumb']?></a> : <a href="/process/">process</a> : donate

<p>The <?=$GLOBALS['site_name']?> is a grassroots organization committed
to using media production and distribution as a tool to promote social and
economic justice. The IMC is a truly cooperative effort of hundreds of
independent journalists and media activists. We are neither owned nor
funded by big conglomerates or advertisers -- that's why we need your 
support to sustain our efforts!</p>

<p>Donation Notes Here:</p>

<blockquote>
Your Site Adress Here
</blockquote>

<h3>or <a href="https://www.paypal.com/xclick/business=paypaladdresshere">donate online via Paypal</a>!</h3>

<p>More Donation Stuff like Computer etc goes here...</p>

<p>Thank you for your support!</p>

<p><small>Last updated <?php echo date("r",filemtime(SF_CACHE_PATH.'/pages/donate.inc')); ?></small></p>

<a href="/"><?=$GLOBALS['site_crumb']?></a> : <a href="/process/">process</a> : donate (<a href="#top">top</a>)
