<div class="bcrumb"><a href="/"><?php echo $GLOBALS['site_crumb']; ?></a> : <a
href="/process/">process</a> : <a href="/process/resources/">making
media</a> : tutorials</div><br>

<div class="hedl"><strong>Audio/Video Encoding Recommendations</strong></div>
<div>
<ol>
<li>plug your DV or Digital8 camera into the computer via FireWire.</li>
<li>open Final Cut Pro.</li>
<li>choose Log and Capture from the File menu.</li>
<li>select the Clip Settings and make sure you are capturing Audio+Video
and the audio format is Stereo. For best results, simply use the DV 
NTSC capture and sequence setting presets.</li>
<li>use the transport controls in the Log and Capture window
to control your camcorder and find the footage you want
to capture.</li>
<li>mark the start and end of your sequence by either Clicking the Mark In
(&gt;|) and Mark Out (|&lt;) buttons, or entering specific timecodes (In
and
Out) in the timecode
fields at the bottom of the window.</li>
<li>name the clip in the Label box, or select Prompt and it will prompt
you.</li>
<li>click the "Clip" button to capture the marked clip.</li>
<li>the clip opens in its own window.</li>

<br><br>at this point, you <i>could</i> drag your clip onto the browser
window and start editing. but we won't get into that here. if you edit,
you will have to export a Final Cut Pro movie (which is actually just a
QuickTime movie containing the audio tracks and links to the captured 
and rendered DV files) and open it in Media Cleaner Pro. For 
faster export, do NOT export a self-contained Final Cut Pro movie.<br><br>

<li>If you aren't editing and exporting a Final Cut Pro movie, then 
save your captured clip somewhere.</li>
<li>quit Final Cut Pro (command-Q).</li>

</ol>
</div>

<div><small>Last updated <?
echo date("r",filemtime($_SERVER['SCRIPT_FILENAME']));
?></small></div><br />

<div class="bcrumb"><a href="/"><?php echo $GLOBALS['site_crumb']; ?></a> : <a
href="/process/">process</a> : <a href="/process/resources/">making
media</a> : tutorial</div>
