<div class="bcrumb"><a href="/"><?php echo $GLOBALS['site_crumb']; ?></a> : <a
href="/process/">process</a> : <a href="/process/resources/">making
media</a> : tutorials</div><br>

<p style="font-family: bookman, gadget"><b>Getting and scheduling the
interview--</b> Don't be shy!  Most authors, activists, organizers,
speakers, politicians, etc. want to get their message out and will be
motivated to talk to you.  They also are often very busy so make your
request very concise and clear.  Tell them how much of their time you will
need and where and when, or if you're flexible.  Be ready to get their
telephone number and give them yours.  If you have a card that's great.  
If not, be sure to write your identifying information-- name, tel., org.,
if any, and what you want-- so when they read it later they will know what
it is. They may well be moving fast so you also must move fast.  If
they're from out of town find out at first how long they will be in town
so you can know how quickly you need to speak with them.</p>

<p style="font-family: bookman, gadget"><b>Equipment--</b> know your tape
recorder and equipment-- in or out of studios.  Practice with it until you
feel comfortable.  It's preferable by far for broadcast quality interviews
to have a Sony TCD5M or a Sony Walkman Pro or a Marantz.  Dats are good
also. These are all quite expensive.  Marantz is the least expensive.
These days I use a Sharp Minidisc Recorder the most because it's small,
affordable and sound is good AND, you can do some editing on it. It is
important to have levels you can see, but if you simply can't afford or
have access to one of these recorders, use the best quality one you can.  
It's best to have an external microphone so you can put it close to the
interviewees mouth.  If you have to use a recorder with a built-in mic
then hold the recorder close to the person's mouth.  Also, be sure to mic
yourself in the same way you mic the interviewee.</p>

<p style="font-family: bookman, gadget">Use headphones always!!!  This is
all about sound.  Even if you can see levels use headphones so you can
hear how it is getting recorded. Sometimes sounds you wouldn't even notice
without headphones come out loud on the tape-- like background sounds,
lip-smacking, wind, refrigerators, air conditioners, fans, etc..  Never
eat during interviews or drink.  Sounds horrible over the air or on tape.  
If you have a choice find a quiet place for the interview.  If not, even
an interview in a noisy crowd can work if you have a good recorder and the
correct microphone techniques and if its part of the story. But don't meet
for lunch and do an interview in a cafe.  A demonstration or out on the
street or in a meeting is ok if its the context of the story.  If
background sounds are constant that's not necessarily a problem.  I really
dislike slamming doors, telephones ringing and people yelling because its
startling to the listener and therefore unpleasant.  If you can't control
it it's sometimes good to refer to what the noise is and where you are so
the listener doesn't get distracted by "wondering".  What's impt. to be
good for the radio is that the person sounds like they are right there
next to the radio listener.  Otherwise, though you might be able to
understand it if you try, it's called "off mic" and the radio listener
will turn it right off because they usually don't want to have work real
hard to understand.  Always remember that most people listen in cars, over
radios that aren't so clear, with other things going on in the room they
are in, while they are washing dishes ........ whatever......... so its
your job to make the sound as clear and crisp as possible.  Also remember
that they tune in and out and are often distracted.  With headphones you
can adjust the sound.  Over time your ears will become more sensitive to
the differences.  With the visual levels I, personally, like to record so
the levels jump into the red sometimes but are mostly at the highest part
of the black.</p>

<p style="font-family: bookman, gadget">If you notice "popping "p's" aim
the mic at the nose or chin of the person.  With most mics its important
to use a windscreen.</p>

<p style="font-family: bookman, gadget">If you're using batteries make
sure they're good because you don't want to have to break the flow of an
interview to change batteries and obviously you don't want the recorder to
die or fade.  Good to have an extension chord and a plug.</p>

<p style="font-family: bookman, gadget">I do interviews I don't edit and I
like to have a timer so I can start it when the interview begins, and
watch how the time is passing so I can know how to direct the interview to
have a beginning , middle and end on time.  That's a big part of my job.  
To make sure that happens with a smooth flow,.  Also it's good to identify
the interviewee (and maybe yourself) at least every 15 minutes because
people tune in at different times and wonder what's going on.  If you're
going to edit you can just let the person go on as long as you and they
have agreed to and have time for, but you still might want to know how
time is passing so you don't find yourself out of time before you have
covered the major points.</p>

<p style="font-family: bookman, gadget">Make the interviewee comfortable
in advance-- both physically and psychically!!-- You should be comfortable
too, but they must be because you want them to not have to think about
anything but their subject and to feel relaxed.  It's good to chat while
you're setting up and use that time to "connect" and get comfortable with
the person and them with you while not taking too much time or being too
"eyeball to eyeball." It's your job to control the microphone!  Tell them
this before you start because a lot of people will try to take the mic to
be helpful.  You are in control and want to stay that way. You must learn
to handle the mic without hand noise which will come onto the tape.  This
is another reason to practice and wear headphones.  You don't want those
sounds on the tape.  I use one mic when interviewing even several people
because 1) I only have one mic and 2) I can control the evenness of the
sound and 3) I know how to hold the mic without moving my hand on the
shaft or if I have to change position I do it carefully so the sound
doesn't get on the tape.  Move from the elbow.  I prefer, when possible,
to have a table to put the recorder on where I can see the levels and not
lose eye contact too much with the person and where I can prop my elbow so
it doesn't get too tired.  I have interviewed people in all kinds of wierd
places and positions because I do the moving and the setting up while
wearing headphones so the sound is ok.  Sometimes I'm uncomfortable but I
try to minimize their awareness of this and I figure it's worth it.  What
and how it's recorded on tape is what is important. Listen for echoes too,
though sometimes you just can't avoid them.  If you can, do.  I've done
many interesting,good sounding interviews sitting on the floor in corners
in halls- even bathrooms, sitting in cars, etc. .</p>

<p style="font-family: bookman, gadget">Once you get the hang of it you
can be very flexible as you often have to be if y ou want to get the
person while you are both available.</p>

<p style="font-family: bookman, gadget">If there are telephones around
make sure you have turned them off or removed them.  If it's somewhere
like a house or office and you can ask others to stay away or be quiet
(like don't move "quiet") or hang a sign on the door not to disturb, do
so.  Agree on the time you want and or have for the interview.</p>

<p style="font-family: bookman, gadget"><b>The actual interview--</b> I
think it's not good to talk about what you're going to talk about.  
Spontaneity is important and repitition can lessen spontaneity.  A few
sentences about the subject are ok beforehand, and if the interviewee is
uptight just reassure them that they know their subject and are sure to be
interesting.  I never show people questions beforehand.  Pick people to
interview who know their subject or don't do it.  They can be any sort of
person-- from illiterate to a Ph.D-- but they should be talking about what
they know about.  I assure nervous interviewees that it will be a
"conversation", not a "test".  There is no right or wrong and it is my job
to move things along.  Which it is.  I should know something about the
subject and presumably I wouldn't be doing the interview if I weren't
interested.  But I don't have to be an expert.  In fact, often it is
counterproductive if I do know a lot because the conversation will be over
the heads of a general audience.  To be interested and to listen are most
important.</p>

<p style="font-family: bookman, gadget">My personal opinion is that it is
good to be responsive to the interviewee.  The interviewer should have
thought about the subject and have some questions in her/his head and/or
on paper but, for me, to ask a question, get an answer, and just move on
to the next question without any response can sound very impolite, stiff
and disjointed.  Always the interviewer should talk much less than the
interviewee but I, personally, prefer some responsiveness and interaction.  
But each interview and person is different and we need to develop our own
styles.  As an activist I almost always interview people whose ideas I
want to get out to the listening audience so I don't play too neutral.  
However it is always important to let the interviewee do the majority of
the talking.  It is the interviewer's job to bring that person out and be
a vehicle by asking, taking responsibility for the technical aspects,
setting up the form if necessary (short identification and description of
what the person does-- organization, writings, teaches and lives where,
how long has been involved, etc..  Don't have to do this all every time- 2
to 5 sentences-- a couple of min. max are fine.  Just to place the person
in a context. Keep those things written in front of you so you don't
forget and can use them again in the outro.)</p>

<p style="font-family: bookman, gadget">Warmth and interest and listening
are extremely important.  If you are sincerely interested and listening
then the interview will flow.  For this you must pay attention to what the
person is saying rather than what your plan is for what to say next.  
This gets easier with experience, but it is crucial.  Eye contact,
contact, connection -- VERY IMPT..  Because I use one mic I tell the
person I need to sit very close and warn them that I control the mic and
that I'm going to have to put it very close to their mouth.  The fact is
that if they look at my eyes they will be less distracted by the mic and
feel more supported by me.  (I don't tell them this.) And, of course,
sincerity is important.  Also very important are nonverbal responses so
the sound doesn't get on the tape, but you are giving the interviewee
positive reinforcement while they speak.  Nod, smile- whatever. VERY
IMPT..  Talking at the same time sounds really bad on the radio or tape.  
Use hand signals if you need to get a word in.  Mention that time is
almost up.  I put up 5 fingers for 5 min. before end and 2 fingers to
signify 2 remaining minutes.  I explain this beforehand and I also ask
beforehand if the person is going to want to give tel. numbers, fax,
address, etc. so we can both be prepared and I can leave time for them.  
Since I don't edit but either of us could have a problem and have to stop
I tell the person to point at the recorder meaning to put it in "pause"
rather than say "turn it off".  If that happens I turn off the recorder
and stop the timer.  When I begin again I start the timer along with the
recorder but start the timer first so the beep of the timer doesn't get
recorded.  If I've forgotten, for example, to turn off the tel. and it
rings, I put the recorder on pause right away, deal with the phone and
when I go back to the recorder I find the last place on the tape that I
can start again, back up the tape to that point, put it on "record" and
"pause" and take off the pause where the interview continues.</p>

<p style="font-family: bookman, gadget">Written by-<br />
Sue Supriano<br />
Email: suesis at attbi dot com</p>

<div><small>Last updated <?php echo date("r",filemtime($_SERVER['SCRIPT_FILENAME'])); ?></small></div><br>

<div class="bcrumb"><a href="/"><?php echo $GLOBALS['site_crumb']; ?></a> : <a
href="/process/">process</a> : <a href="/process/resources/">making
media</a> : tutorial</div>
