<div class="h1">live chat</div>

<div>Indymedia operates a 24-hour chatroom for discussion and technical
  support. You will usually find someone hanging out in the channels. If not, 
  there is an automated bot which can also provide assistance! We use Internet
  Relay Chat (IRC) for our chatroom. You can access the chat with your own client 
  program, or use our <a href="http://irc.indymedia.org/sf/">Java applet interface</a> 
  on your browser.</div><br />

<table width="75%" border="0" cellspacing="2" cellpadding="2">

  <tr>
    <td class="bgaccent"><b>CONNECT 
      RIGHT AWAY!</b></td>
  </tr>

  <tr>
    <td class="bgsearchgrey" valign="middle">To begin chatting right away, go to <a href="http://chat.indymedia.org">
	chat.indymedia.org</a> and choose either the java-applet or the html-interface. 
    </td>
  </tr>
</table>
<br />
<table width="75%" border="0" cellspacing="2" cellpadding="2">
  <tr> 
    <td class="bgaccent"><b>DOWNLOAD 
      A CLIENT</b></td>
  </tr>
  <tr> 
    <td class="bgsearchgrey" valign="middle">If 
      you do not have a Java-enabled browser, you can download your own irc client. 
      This is a program that runs on your computer and allows you to connect to 
      our chat server. You will want to take note of the following settings:<br />
      <b>IRC Hostname:</b> irc.indymedia.org<br />
      <b>Channel:</b> #sf<br />
      <br />
      Refer to this table to find an IRC client:<br />
      <table width="100%" border="0" cellspacing="2" cellpadding="2">
        <tr> 
          <td width="15%" valign="top"><b>Windows:</b></td>
          <td>Probably the 
            easiest-to-use IRC client for Windows is a free program called mirc: 
            <a href="http://www.mirc.co.uk/get.html">download</a>. Check <a 
href="http://download.cnet.com/downloads/1,10150,0-10001-103-0-1-7,00.html?tag=srch&amp;qt=IRC&amp;cn=Internet&amp;ca=10001">here</a> 
            for more programs.</td>
        </tr>
        <tr> 
          <td width="15%" valign="top"><b>Macintosh:</b></td>
          <td>There is a review 
            of Mac IRC clients <a href="http://www.ex.ac.uk/%7Ejastaple/irc/irchelp.html">here</a>. 
            You can find a more current list <a 
href="http://versiontracker.com/mp/new_search.m?OS_Filter=MacOS&search=irc&order_d=D&order=DateMod">here</a>.</td>
        </tr>
        <tr> 
          <td width="15%" valign="top"><b>Unix:</b></td>
          <td>We highly recommend 
            <a href="http://www.epicsol.org/">epic</a>!</td>
        </tr>
      </table>
    </td>
  </tr>
</table>
