<div class="bcrumb"><a href="/"><?php echo $GLOBALS['site_crumb']; ?></a>  : <a href="/process/">process</a> : links</div>

<h2>Links</h2>
<ul><li><small><a href="#sf_news">Independent News</a></small></li>
<li><small><a href="#sf_media">Media Organizations</a></small></li>
<li><small><a href="#sf_activist">Activist Organizations</a></small></li>
<li><small><a href="#world_news">News and Activist Organizations Worldwide</a></small></li></ul>

<a name="sf_news"></a><h2>Independent News</h2>

<ul>
	<li><b><a href="http://yourfavoritewebsite.com/">Your Website here</a></b>: Descripton of the side goes here.</li>
</ul>

<a name="sf_media"></a><h2>Media Organizations in SF Bay Area</h2>
<ul>
	<li><b><a href="http://yourfavoritewebsite.com/">Your Website here</a></b>: Descripton of the side goes here.</li>
</ul>

<a name="sf_activist"></a>
<h2>Activist Organizations in SF Bay Area</h2>

<ul>
	<li><b><a href="http://yourfavoritewebsite.com/">Your Website here</a></b>: Descripton of the side goes here.</li>
</ul>

<p><small>Last updated <? echo date("r",filemtime($_SERVER['SCRIPT_FILENAME'])); ?></small></p>
<div class="bcrumb"><a href="/"><?php echo $GLOBALS['site_crumb']; ?></a>  : <a href="/process/">process</a> : links</div>
