<blockquote class="summary">Summary of your local Editorial Policy</blockquote>

<h3>Fundamentals</h3>
<p><a href="http://www.cat.org.au/maffew/cat/openpub.html">Open Publishing</a>

<p>Here comes your editorial policy. Have a look on all the other policys at the indymedia network!

<h3>Consensus</h3>
<h3>Administration</h3>
<h3>Editorial Process</h3>
<h3>Commenting</h3>
<h3>Spam Attacks</h3>

<h3>Contact</h3>

<p><small>Last updated <? echo date("r",filemtime(SF_CACHE_PATH."/pages/openpub.inc")); ?></small></p>
