<h3>Privacy Policy</h3>

<p>This Site intends to give you the user as much control as possible over your personal information...</p>

<h4>NOTICE</h4>
<p>The web server does not normally track the domains or IP addresses from which people visit and/or post to the web site. Usage of other services, however, may be logged...</p>

<h4>CHOICE</h4>
<a href="/process/privacy.php">http://<? echo $SERVER_NAME; ?>/process/privacy.php</a>.</p>

<p><small>Last updated <? echo date("r",filemtime(SF_CACHE_PATH.'/pages/privacy.inc')); ?></small></p>
