<a href="/"><?=$GLOBALS['site_crumb']?></a> : process
<br />
<br />
<h3 class="h3">Mission Statement</h3>
The <a href="about.php">mission statement</a> defines what we are and what
we do.<br /><br />

<h3 class="h3">Contact Us / Get Involved</h3> Questions? Comments? <a
href="contact.php">Contact us</a>! Want to get involved? <a
href="http://volunteer.indymedia.org/">Introduce yourself</a>, and
subscribe to our <a href="http://lists.indymedia.org/">lists</a>.<br /><br />

<h3 class="h3">Upcoming Meetings</g3> 

<p>....<p>

<p><?php include(SF_CACHE_PATH.'/contact.html'); ?></p>

<h3 class="h3">Visit the IMC Space</h3>
<p>Our community media production space in the Mission District is <a
href="/process/spaces/">open</a>.</p>

<h3 class="h3">Get your video/media to IMC</h3>
<p> Text </p>

<h3 class="h3">Media Production Resources</h3> 
<p><a
href="resources/">Tutorials, local facilities and
resources, and workshops.</a></p>

<h3 class="h3">SF-IMC Intranet</h3>
<p>Various SF-IMC project management pages are located at <a
href="http://sfimc.net/">sfimc.net</a>.</p>

<h3 class="h3">Indymedia Chat</h3>

<p>Create your own chat channel or join the #sf discussion at <a
href="/irc/">irc.indymedia.org</a>.</p>

<h3 class="h3">Documents</h3>
<p><a href="/process/donate.php">Donating to SF-IMC</a> |
<a href="/process/openpub.php">Editorial policy</a> |
<a href="/process/disclaimer.php">Legal info</a> |
<a href="/process/links.php">Links &amp; allies</a> |
<a href="/process/privacy.php">Privacy policy</a> |
<a href="http://sfimc.net/uploads/vol_orientation_handout.pdfpvyrs3.pdf">Volunteer info [PDF]</a>

<p><small>Last updated <?php echo date("r",filemtime(SF_CACHE_PATH.'/pages/process.inc')); ?></small></p>

<a href="/"><?=$GLOBALS['site_crumb']?></a> : process <a href="#top">(top)</a>
