<a href="/"><?php echo $GLOBALS['site_crumb']; ?></a> : <a href="/process/">process</a> : spaces

<p>Intro.</p>

<table align="right" cellspacing="0" cellpadding="3" border="1">
<caption>Open Hours</caption>
<tr><th align="right">Mon</th><td align="right">4:00pm-7:00pm</td></tr>
<tr><th align="right">Wed</th><td align="right">12:00pm-7:30pm</td></tr>
<tr><th align="right">Thu</th><td align="right">12:00pm-5:00pm</td></tr>
</table>

<h4>IMC Space</h4>

<p>Text</p>

<h4>Other Facilities and Resources</h4>

<p>Description</p>

<p>&nbsp;</p>

<p><small>Last updated <? echo date("r",filemtime(SF_CACHE_PATH.'/pages/spaces_index.inc')); ?></small></p>

<a href="/"><?php echo $GLOBALS['site_crumb']; ?></a> : <a href="/process/">process</a> : spaces <a href="#top">(top)</a>
