<h3>Themes</h3>

<p>We allow you to choose among several themes, comprised of colors, 
fonts, and other presentation attributes. To use the theme feature, 
your browser must accept cookies and CSS (cascading style sheets); 
any 4th generation or higher web browser should be up to the task.</p>

<table class="bgult" cellpadding="0" cellspacing="0" border="0">
<tr><td><table cellpadding="2" cellspacing="1" border="0">

<tr>
<td class="bgsearchgrey">
<a href="/theme.php?theme=default">
<img alt="white theme" align="middle" src="/images/box-white.gif" width="13" height="13" border="0" /> <em>default</em></a>
</td>

<td class="bgsearchgrey"><a href="/theme.php?theme=1">
<img align="middle" src="/images/box-black.gif" alt="black theme" width="13" height="13" border="0" /> <em>classic</em></a>
</td>

<td class="bgsearchgrey"><a href="/theme.php?theme=2">
<img src="/images/box-red.gif" alt="red theme" width="13" height="13" align="middle" border="0" /> <em>revolution</em></a>
</td>

<td class="bgsearchgrey"><a href="/theme.php?theme=9">9</a> 
<a href="/theme.php?theme=9"><em>blood</em></a></td>

<td class="bgsearchgrey"><a href="/theme.php?theme=7">7</a> 
<a href="/theme.php?theme=7"><em>verdana</em></a></td>
</tr>

<tr>
<td class="bgsearchgrey"><a href="/theme.php?theme=3">
<img align="middle" src="/images/box-white.gif" alt="white serif theme" width="13" height="13" border="0" /> <em>serif</em></a>
</td>

<td class="bgsearchgrey"><a href="/theme.php?theme=4">
<img align="middle" src="/images/box-black.gif" alt="black serif theme" width="13" height="13" border="0" /> <em>classic serif</em></a>
</td>

<td class="bgsearchgrey"><a href="/theme.php?theme=5">
<img align="middle" src="/images/box-red.gif" alt="red serif theme" width="13" height="13" border="0" /> <em>rev serif</em></a>
</td>

<td class="bgsearchgrey"><a href="/theme.php?theme=6">6</a> 
<a href="/theme.php?theme=6"><em>alternative</em></a>
</td>

<td class="bgsearchgrey"><a href="/theme.php?theme=8">8</a> 
<a href="/theme.php?theme=8"><em>chicago</em></a>
</td>

</tr>
</table>
</td></tr></table>

Contact the <a href="mailto:yourlist@indymedia.org">design collective</a> if you would like to contribute a new 
theme.

<p>Your theme preference is stored on your computer as a cookie file,
which is accessed by our web server each time you visit a page on the
site. No other data is stored in the cookie, and we do not
track any identifying information about you or your computer. Please read
our <a href="/process/privacy.php">privacy policy</a> if you have any
questions.</p>
