<div class="bcrumb"><a href="/"><?php echo $GLOBALS['site_crumb']; ?></a> : <a
href="/process/">process</a> : making media</div><br>

<div class="hedl"><strong>Publish!</strong></div>
<div>The Independent Media Center allows anyone to
instantaneously <a href="/publish.php">publish</a> articles, photos,
audio and video on the website.</div><br>

<div class="hedl"><strong>IMC</strong></div><div> 
Space Description  <a
href="/process/spaces/">Click for more info and open hours.</a></div><br>

<div class="hedl"><strong>Send/Bring Your Media to the IMC</strong></div>
<div>Get your media to IMC for editing and publishing on the web.
Photos, articles, audio and <b>video in any format</b> (mini dv or vhs
preferred) are requested.  Mailto: Contact Adress</div><br />

<div class="hedl"><strong>Online Tutorials</strong></div>
<div>Interested in publishing audio/video on the site? Read our <a
href="encoding.php">encoding tutorial</a> - including links to general
FAQs and our site-specific recommendations. Also available: 
<a href="interviewing.php">interviewing tips</a>, <a 
href="finalcut.php">Final Cut Pro tutorial</a>, and <a 
href="cleaner.php">Cleaner tutorial</a>.</div><br>

<div class="hedl"><strong>Independent Media
Calendars</strong></div> <div>Check out our <a
href="/calendar/event_display_list.php?type_id=3&detail_flag=on">video
screening</a> and <a
href="/calendar/event_display_list.php?type_id=12&detail_flag=on">radio
broadcast</a> calendars and add your listings!</div><br />

<div class="hedl"><strong>Get Connected</strong></div>
<div>If you'd like to get involved in IMC audio or video production in the
bay area, please join the <a
href="http://lists.indymedia.org/mailman/listinfo/imc-yourlist-audio/">imc-yourlist-audio</a>
or <a
href="http://lists.indymedia.org/mailman/listinfo/imc-yourlist-video/">imc-yourlist-video</a>
 listservs.</div>

<div><small>Last updated <?php echo date("r",filemtime(SF_CACHE_PATH.'/pages/tutorial_index.inc')); ?></small></div><br>

<div class="bcrumb"><a href="/"><?php echo $GLOBALS['site_crumb']; ?></a> : <a
href="/process/">process</a> : making media <a 
href="#top">(top)</a></div>
