<a href="http://www.indymedia.org/">www.indymedia.org</a>
 
<b>africa:</b>

<b>canada:</b>
 <a href="http://quebec.indymedia.org/">quebec</a>

<b>east asia:</b>
 <a href="http://japan.indymedia.org/">japan</a>

<b>europe:</b>
 <a href="http://athens.indymedia.org/">athens</a>
 <a href="http://barcelona.indymedia.org/">barcelona</a>
 <a href="http://belgium.indymedia.org/">belgium</a>
 <a href="http://bristol.indymedia.org/">bristol</a>
 <a href="http://bxl.indymedia.org">brussels</a>
 <a href="http://cyprus.indymedia.org">cyprus</a>
 <a href="http://de.indymedia.org/">germany</a>
 <a href="http://grenoble.indymedia.org">grenoble</a>
 <a href="http://www.indymedia.ie/">ireland</a>
 <a href="http://istanbul.indymedia.org/">istanbul</a>
 <a href="http://lille.indymedia.org">lille</a>
 <a href="http://linksunten.indymedia.org">linksunten</a>
 <a href="http://nantes.indymedia.org">nantes</a>
 <a href="http://indymedia.nl">netherlands</a>
 <a href="http://www.indymedia.no/">norway</a>
 <a href="http://pt.indymedia.org/">portugal</a>
 <a href="http://www.indymedia.org.uk/">united kingdom</a>

<b>latin america:</b>
<a href="http://argentina.indymedia.org/">argentina</a>
 <a href="http://www.midiaindependente.org">cmi brasil</a>
 <a href="http://rosario.indymedia.org/">rosario</a>

<b>oceania:</b>
 <a href="http://www.indymedia.org.nz/">aotearoa</a>

<b>united states:</b>
 <a href="http://austin.indymedia.org/">austin</a>
 <a href="http://bigmuddyimc.org/">big muddy</a>
 <a href="http://binghamton.indymedia.org">binghamton</a>
 <a href="http://boston.indymedia.org/">boston</a>
 <a href="http://chicago.indymedia.org/">chicago</a>
 <a href="http://columbus.indymedia.org">columbus</a>
 <a href="http://la.indymedia.org/">la</a>
 <a href="http://www.michiganimc.org/">michigan</a>
 <a href="http://nyc.indymedia.org/">nyc</a>
 <a href="http://portland.indymedia.org/">portland</a>
 <a href="http://rochester.indymedia.org/">rochester</a>
 <a href="http://reboot.stlimc.org">saint louis</a>
 <a href="http://sandiego.indymedia.org/">san diego</a>
 <a href="http://www.indybay.org/">san francisco bay area</a>
 <a href="http://www.indybay.org/santacruz/">santa cruz, ca</a>
 <a href="http://tnimc.org/">tennessee</a>
 <a href="http://www.ucimc.org/">urbana-champaign</a>
 <a href="http://worcester.indymedia.org">worcester</a>

<b>west asia:</b>
 <a href="http://www.indymedia.org/en/static/palestine">palestine</a>

<b>process:</b>
<a href="http://www.indymedia.org/fbi/">fbi/legal updates</a>
 <a href="http://docs.indymedia.org/">process & imc docs</a>

<b>projects:</b>
 <a href="http://radio.indymedia.org/">radio</a>
 <a href="http://satellite.indymedia.org/">satellite tv</a>
 
